### ISSUE TITLE
in games command doesnt work

### ISSUE THREAD

**Issue by AllahGamingYT** [fedddddd/node-server-manager#3]
I can do setmoney, give etc within the console yet ingames commands doesn't work even though I use correct prefix, I tried everything.

**Comment by AllahGamingYT** [comment]
here's my config
`{
    "Webfront": true,
    "WebfrontPort": 8080,
    "WebfrontSSL": false,
    "WebfrontSSL-Key": "",
    "WebfrontSSL-Cert": "",
    "webfrontHostname": "",
    "discordHookUrl": "",
    "MOTD": "No message of the day today :(",
    "Info": "No info for now...",
    "commandPrefixes": [
        "."
    ],
    "broadcastCommandPrefixes": [
        "@"
    ],
    "links": [],
    "socialMedia": [],
    "rules": [],
    "locale": "en",
    "autoMessagesInterval": 60,
    "autoMessages": [
        "A total of ^5{TOTALCLIENTS}^7 players have played on this server",
        "Join the discord at ^5discord.gg/^7!",
        "This server uses ^1Node Server Manager^7 get it at ^5github.com/fedddddd/node-server-manager^7",
        "There are ^5{PLAYERCOUNT}^7 online players across ^5{SERVERCOUNT}^7 servers at the moment",
        "^5{TOTALKILLS}^7 players have been killed on this server",
        "^5{TOTALPLAYEDTIME}^7 hours have been wasted playing on this server"
    ],
    "Servers": [
        {
            "IP": "localhost",
            "PORT": "4978",
            "PASSWORD": "myrcon",
            "LOGFILE": "logs.log",
            "Gamename": "T6",
            "reservedSlots": 0
        }
    ],
    "Permissions": {
        "Levels": {
            "ROLE_BANNED": -1,
            "ROLE_USER": 0,
            "ROLE_FLAGGED": 1,
            "ROLE_TRUSTED": 2,
            "ROLE_MODERATOR": 3,
            "ROLE_ADMIN": 4,
            "ROLE_OWNER": 5,
            "ROLE_MANAGER": 6
        },
        "Commands": {
            "COMMAND_KICK": "ROLE_MODERATOR",
            "COMMAND_USER_CMDS": "ROLE_USER",
            "COMMANDS_KICK": "ROLE_MODERATOR",
            "COMMAND_FIND": "ROLE_MODERATOR",
            "COMMAND_SETROLE": "ROLE_ADMIN",
            "COMMAND_TP": "ROLE_ADMIN",
            "COMMAND_RCON": "ROLE_OWNER",
            "COMMAND_TOKEN": "ROLE_MODERATOR",
            "COMMAND_BAN": "ROLE_MODERATOR",
            "COMMAND_CHANGE_INFO": "ROLE_ADMIN",
            "COMMAND_MAP": "ROLE_ADMIN"
        },
        "Roles": {
            "ROLE_BANNED": "Banned",
            "ROLE_USER": "User",
            "ROLE_FLAGGED": "Flagged",
            "ROLE_TRUSTED": "Trusted",
            "ROLE_MODERATOR": "Moderator",
            "ROLE_ADMIN": "Admin",
            "ROLE_OWNER": "Owner",
            "ROLE_MANAGER": "Node Server Manager"
        }
    }
}`

**Comment by fedddddd** [comment]
Please read the documentation before going as far as opening issues.

You didn't set the correct path for the server's logfile.
From the readme:
> Server Log File path: Path of the server's logfile

This means something like `C:\t6-server\t6\logs\games_mp.log` or wherever your log file is.
