### ISSUE TITLE
Roles in node-server-manager

### ISSUE THREAD

**Issue by I3lackExo** [fedddddd/node-server-manager#5]
Hey fedddddd,

I have a problem creating roles because I want to add more roles. They are marked with -1 to 6 but how do I get more rolls with other numbers?

xX-LulzSecC4t-Xx

**Comment by alicealys** [comment]
You can't/aren't supposed to add more roles, however you can add them using [node-server-manager-v2](https://github.com/fedddddd/node-server-manager-v2) though this version is still unfishished.

**Comment by I3lackExo** [comment]
I had already installed and also according to instructions but had an error because I could not fix. In addition, I had set 0 in the roles I made and that in 0.1, 0.2, 0.3, ... but in the role at the ClanTag.dll the following is displayed: [.1God]xX-LulzSecC4t-Xx

xX-LulzSecC4t-Xx

**Comment by I3lackExo** [comment]
![Uploading Screenshot_9.png…]()

**Comment by I3lackExo** [comment]
I installed it but idk how i bind it with ClanTagRank.dll

**Comment by alicealys** [comment]
Like I said it's unfinished and either way it's intended more for general purpose so I won't add support for such game specific features.

**Comment by I3lackExo** [comment]
Hm okay
