### ISSUE TITLE
NodeLogServer Error at Line 1 

### ISSUE THREAD

**Issue by THS-Shiniri** [fedddddd/node-server-manager#6]
I´ll get an Error (Syntax) with the following code: 800A03EA

I really want to use NSM on my secondary VPS with the same Database from my main VPS so I wanted to use NLS the JSON config is made and in Configurations DIR saved. But I can not even start the NLS.js in Lib DIR.

Neither can I start the .sh in the root folder it just pops up shortly and quits.

Any suggestion ?

**Comment by THS-Shiniri** [comment]
![msedge_gBlNeiepE7](https://user-images.githubusercontent.com/95319615/145086072-ab0405ce-4d87-44a2-9a3d-7753df10cb30.png)

**Comment by alicealys** [comment]
You have to use the .bat script not he .sh

**Comment by THS-Shiniri** [comment]
Which bat ? I have downloaded it with git clone and I only have the .js and .sh no batch at all O.o

![image](https://user-images.githubusercontent.com/95319615/145275579-b19c5e6b-c4b1-4abf-a382-2b2818338cb8.png)

**Comment by alicealys** [comment]
StartLogServer.bat

**Comment by alicealys** [comment]
Nevermind I just realized it's fucked up

**Comment by alicealys** [comment]
Reclone and it should be there (`StartLogServer.bat`)

**Comment by THS-Shiniri** [comment]
When I use the batch I still get this error
![image](https://user-images.githubusercontent.com/95319615/145294297-d48acd2f-d042-4df4-9472-5cf960effee2.png)

NLS Config:

{
  "Servers": [
    {
      "bindPort" : 9997,
      "logFile" : "/Users/Username/AppData/Local/Plutonium/storage/t6/logs/games_zm_private_2.log",
      "key" : "XXXX",
    }
  ]
}

**Comment by THS-Shiniri** [comment]
Nevermind I am just dump and forgot to remove the "," works now thank you!
